name: chatapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  delightful_toast: ^1.1.0
  image_picker: ^1.1.2
  mime: ^1.0.0
  http_parser: ^4.0.0
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.2
  flutter_chat_bubble: ^2.0.2
  socket_io_client: ^3.0.2
  cupertino_icons: ^1.0.8
  wechat_assets_picker: ^9.4.2
  provider: ^6.1.2
  path: ^1.8.3
  video_player: ^2.9.2
  waveform_recorder: ^1.4.0
  voice_message_package: ^2.2.1
  flutter_markdown: ^0.7.5
  any_link_preview: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
